const adminProducts=[
['ChatGPT Plus','AI Assistants','Rs. 2,300','openai'],['Gemini Pro','AI Assistants','Rs. 800','googlegemini'],['Veo 3 Ultra','AI Video','Rs. 2,100','google'],['Leonardo AI Essential','Design','Rs. 1,900','leonardoai'],['ElevenLabs','AI Voice','Rs. 3,300','elevenlabs'],['Canva Pro Edu','Design','Rs. 900','canva'],['Figma Pro Private','Design','Rs. 3,000','figma'],['CapCut Pro','AI Video','Rs. 900','capcut'],['Adobe Creative Cloud','Design','Rs. 1,700','adobecreativecloud']
];
function adminLogo(name){const mark=name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();return `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 60 60"><rect width="60" height="60" rx="14" fill="#193b30"/><text x="30" y="37" text-anchor="middle" font-family="Arial" font-weight="700" font-size="20" fill="#b8f255">${mark}</text></svg>`)}`}
document.querySelector('#adminProducts').innerHTML=adminProducts.map(p=>`<tr><td><div class="product-cell"><img src="${adminLogo(p[0])}" alt=""><span><b>${p[0]}</b><small>Updated today</small></span></div></td><td>${p[1]}</td><td><b>${p[2]}</b></td><td><span class="status">In stock</span></td><td><button class="edit">•••</button></td></tr>`).join('');
const dialog=document.querySelector('#productDialog');document.querySelector('#addProduct').onclick=()=>dialog.showModal();document.querySelector('#demoSave').onclick=e=>{e.preventDefault();dialog.close();alert('Demo mode: connect a database to publish catalog changes across the live store.')};
const wa=document.querySelector('#waNumber');const savedWhatsApp=localStorage.getItem('atg-whatsapp');wa.value=(!savedWhatsApp||savedWhatsApp==='923001234567')?'923476242709':savedWhatsApp;document.querySelector('#saveSettings').onclick=()=>{localStorage.setItem('atg-whatsapp',wa.value.replace(/\D/g,''));document.querySelector('#saveNote').textContent='Saved. Refresh the storefront to apply.'};
document.querySelectorAll('.edit').forEach(button=>button.onclick=()=>{dialog.querySelector('h2').textContent='Edit product';dialog.showModal()});
document.querySelectorAll('nav button').forEach(button=>button.onclick=()=>{document.querySelectorAll('nav button').forEach(item=>item.classList.remove('active'));button.classList.add('active')});
